name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - {
            name: "Windows Latest MinGW",
            artifact: "Windows-MinGW.tar.xz",
            os: windows-latest,
            cc: "gcc",
            cxx: "g++"
          }
        - {
            name: "Ubuntu Latest GCC",
            artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            cc: "gcc",
            cxx: "g++"
          }
        - {
            name: "macOS Latest Clang",
            artifact: "macOS.tar.xz",
            os: macos-latest,
            cc: "clang",
            cxx: "clang++"
          }
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Installing vcpkg (windows only)
      if: ${{ runner.os == 'Windows' }}
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2020.01
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install cppzmq:x64-windows
    
    - name: Running cmake
      run: |
        cd ${{ github.workspace }}

        cmake . -B build
        cmake --build build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.artifact }}
        path: build/app*

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2

    - name: Upload to Release
      uses: meeDamian/github-release@2.0
      with:
        files: >
          Windows-MSVC.tar.xz
          Windows-MinGW.tar.xz
          Linux.tar.xz
          macOS.tar.xz
        gzip: folders
        token: ${{ secrets.GITHUB_TOKEN }}
